### ISSUE TITLE
Feature/persistent maps and boundaries

### ISSUE THREAD

**Issue by ifeign** [Pmant/node-botvac#9]
Adding support for persistent maps and boundaries including getting the persistent maps, getting the boundaries, setting the boundaries, cleaning a (polygon type) boundary (zone) would be very beneficial to your module. This would allow for zone and spot cleaning support with plugins that use node-botvac.

**Comment by Pmant** [comment]
see https://github.com/Pmant/node-botvac/pull/8#issuecomment-509392474

Please note that I currently have no botvac for testing.

**Comment by Pmant** [comment]
I'll keep this open for future bug reports related to the new feature.
